/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.BlockControl;
import Control.DeleteControl;
import Control.EditControl;
import Model.DBCon;
import Model.DBSearch;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author pc
 */
public class Block extends javax.swing.JInternalFrame {
    Statement stmt;
    ResultSet rs ;

    /**
     * Creates new form Projects
     */
    public Block() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lID = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        btnTemp = new javax.swing.JButton();
        pnlBase = new javax.swing.JPanel();
        lblLandManagement = new javax.swing.JLabel();
        tbpBlock = new javax.swing.JTabbedPane();
        pnlBlock = new javax.swing.JPanel();
        pnlNewBlock = new javax.swing.JPanel();
        lblAddBlock = new javax.swing.JLabel();
        lblBlockId = new javax.swing.JLabel();
        txtBlockId = new javax.swing.JTextField();
        lblBlockSize = new javax.swing.JLabel();
        txtBlockSize = new javax.swing.JTextField();
        txtBlockCost = new javax.swing.JTextField();
        lblBlockEstValue = new javax.swing.JLabel();
        txtBlockEstValue = new javax.swing.JTextField();
        lblBlockAvailability = new javax.swing.JLabel();
        btnAddBlock = new javax.swing.JButton();
        btnUndoBlock = new javax.swing.JButton();
        lblBlockCost = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLand1 = new javax.swing.JTable();
        cmbUnit = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        lblBlockId2 = new javax.swing.JLabel();
        prd = new javax.swing.JComboBox<>();
        pnlEditBlock = new javax.swing.JPanel();
        pnlNewBlock1 = new javax.swing.JPanel();
        lblAddBlock1 = new javax.swing.JLabel();
        lblBlockId1 = new javax.swing.JLabel();
        txtBlockId1 = new javax.swing.JTextField();
        lblBlockSize1 = new javax.swing.JLabel();
        txtBlockCost1 = new javax.swing.JTextField();
        lblBlockEstValue1 = new javax.swing.JLabel();
        txtBlockEstValue1 = new javax.swing.JTextField();
        lblBlockAvailability1 = new javax.swing.JLabel();
        btnAddBlock1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblBlockCost1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLand2 = new javax.swing.JTable();
        txtBlockSize2 = new javax.swing.JTextField();
        cmbUnit2 = new javax.swing.JComboBox<>();
        cmbUnit3 = new javax.swing.JComboBox<>();
        btnTemp1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1316, 609));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1198, 36, -1, -1));

        lID.setText("ID");
        getContentPane().add(lID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1031, 82, 96, -1));

        lName.setText("Name");
        getContentPane().add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1031, 48, 96, -1));

        btnTemp.setText("temp");
        btnTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempActionPerformed(evt);
            }
        });
        getContentPane().add(btnTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 564, -1, -1));

        pnlBase.setPreferredSize(new java.awt.Dimension(985, 582));
        pnlBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLandManagement.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblLandManagement.setText("Manage Block");
        pnlBase.add(lblLandManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 6, -1, -1));

        tbpBlock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        pnlBlock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pnlNewBlock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddBlock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddBlock.setText("Add A New Land Block");
        pnlNewBlock.add(lblAddBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 9, -1, -1));

        lblBlockId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockId.setText("Block Id");
        pnlNewBlock.add(lblBlockId, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 36, -1, -1));
        pnlNewBlock.add(txtBlockId, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 31, 193, 36));

        lblBlockSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockSize.setText("Size");
        pnlNewBlock.add(lblBlockSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 171, 75, -1));

        txtBlockSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlockSizeActionPerformed(evt);
            }
        });
        pnlNewBlock.add(txtBlockSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 157, 122, 36));

        txtBlockCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlockCostActionPerformed(evt);
            }
        });
        pnlNewBlock.add(txtBlockCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 211, 193, 36));

        lblBlockEstValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockEstValue.setText("Estimated Value");
        pnlNewBlock.add(lblBlockEstValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 270, 130, -1));

        txtBlockEstValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlockEstValueActionPerformed(evt);
            }
        });
        pnlNewBlock.add(txtBlockEstValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 265, 193, 36));

        lblBlockAvailability.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockAvailability.setText("Availability");
        pnlNewBlock.add(lblBlockAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 320, 130, -1));

        btnAddBlock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddBlock.setText("Add");
        btnAddBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBlockActionPerformed(evt);
            }
        });
        pnlNewBlock.add(btnAddBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 364, 166, 42));

        btnUndoBlock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUndoBlock.setText("Clear");
        btnUndoBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoBlockActionPerformed(evt);
            }
        });
        pnlNewBlock.add(btnUndoBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 364, 166, 42));

        lblBlockCost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockCost.setText("Cost");
        pnlNewBlock.add(lblBlockCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 225, 75, -1));

        tblLand1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Block ID", "Size", "Cost", "Estimated Value", "Availability"
            }
        ));
        jScrollPane2.setViewportView(tblLand1);

        pnlNewBlock.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 105, 937, 310));

        cmbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acres", "Roods", "Perches" }));
        cmbUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnitActionPerformed(evt);
            }
        });
        pnlNewBlock.add(cmbUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 167, 82, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        pnlNewBlock.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 320, 193, -1));

        lblBlockId2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockId2.setText("Project ID");
        pnlNewBlock.add(lblBlockId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, -1, -1));

        prd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prdActionPerformed(evt);
            }
        });
        pnlNewBlock.add(prd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 193, -1));

        javax.swing.GroupLayout pnlBlockLayout = new javax.swing.GroupLayout(pnlBlock);
        pnlBlock.setLayout(pnlBlockLayout);
        pnlBlockLayout.setHorizontalGroup(
            pnlBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBlockLayout.setVerticalGroup(
            pnlBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBlockLayout.createSequentialGroup()
                .addComponent(pnlNewBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpBlock.addTab("+New", pnlBlock);

        lblAddBlock1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddBlock1.setText("Edit A Land Block");

        lblBlockId1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockId1.setText("Block Id");

        lblBlockSize1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockSize1.setText("Size");

        txtBlockCost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlockCost1ActionPerformed(evt);
            }
        });

        lblBlockEstValue1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockEstValue1.setText("Estimated Value");

        lblBlockAvailability1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockAvailability1.setText("Availability");

        btnAddBlock1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddBlock1.setText("Update");
        btnAddBlock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBlock1ActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblBlockCost1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockCost1.setText("Cost");

        tblLand2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Block ID", "Size", "Cost", "Estimated Value", "Availability"
            }
        ));
        tblLand2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLand2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLand2);

        txtBlockSize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlockSize2ActionPerformed(evt);
            }
        });

        cmbUnit2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acres", "Roods", "Perches" }));
        cmbUnit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnit2ActionPerformed(evt);
            }
        });

        cmbUnit3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbUnit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnit3ActionPerformed(evt);
            }
        });

        btnTemp1.setText("temp");
        btnTemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewBlock1Layout = new javax.swing.GroupLayout(pnlNewBlock1);
        pnlNewBlock1.setLayout(pnlNewBlock1Layout);
        pnlNewBlock1Layout.setHorizontalGroup(
            pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                .addComponent(btnAddBlock1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTemp1)
                .addGap(408, 408, 408))
            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(lblAddBlock1))
                            .addComponent(lblBlockSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                .addComponent(lblBlockEstValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBlockEstValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                .addComponent(lblBlockAvailability1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbUnit3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNewBlock1Layout.createSequentialGroup()
                                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNewBlock1Layout.createSequentialGroup()
                                        .addComponent(lblBlockCost1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)
                                        .addComponent(txtBlockCost1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNewBlock1Layout.createSequentialGroup()
                                        .addComponent(lblBlockId1)
                                        .addGap(102, 102, 102)
                                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBlockId1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                                .addComponent(txtBlockSize2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(59, 59, 59)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlNewBlock1Layout.setVerticalGroup(
            pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblAddBlock1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBlockId1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBlockId1))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlockSize1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBlockSize2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlockCost1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBlockCost1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlockEstValue1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBlockEstValue1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBlockAvailability1)
                            .addComponent(cmbUnit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTemp1)
                    .addComponent(btnAddBlock1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlEditBlockLayout = new javax.swing.GroupLayout(pnlEditBlock);
        pnlEditBlock.setLayout(pnlEditBlockLayout);
        pnlEditBlockLayout.setHorizontalGroup(
            pnlEditBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNewBlock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlEditBlockLayout.setVerticalGroup(
            pnlEditBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditBlockLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnlNewBlock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tbpBlock.addTab("Update", pnlEditBlock);

        pnlBase.add(tbpBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, -1, -1));

        getContentPane().add(pnlBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, 1381, 562));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBlockSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlockSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlockSizeActionPerformed

    private void txtBlockCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlockCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlockCostActionPerformed

    private void btnAddBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBlockActionPerformed
        // TODO add your handling code here:
        // Get data from fields
        String BlockID= txtBlockId.getText().toString();
        String BlockSize= txtBlockSize.getText().toString();
        String Cost= txtBlockCost.getText().toString();
        String EstValue= txtBlockEstValue.getText().toString();

        if(BlockID.equals("")){
            JOptionPane.showMessageDialog(null,"Block ID is Mandetory");
        }
        if(BlockSize.equals("")){
            JOptionPane.showMessageDialog(null,"Block Size is Mandetory");
        }
        if(Cost.equals("")){
            JOptionPane.showMessageDialog(null,"Cost is Mandetory");
        }
        if(EstValue.equals("")){
            JOptionPane.showMessageDialog(null,"Estimated Value is Required");
        }
        else
        {

            //String Unit = cmbUnit.getSelectedItem().toString();
            String Status = cmbStatus.getSelectedItem().toString();

            BlockControl.addBlocks(txtBlockId.getText(),txtBlockSize.getText(),txtBlockCost.getText(),txtBlockEstValue.getText(),Status);
        }

    }//GEN-LAST:event_btnAddBlockActionPerformed

    private void btnUndoBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoBlockActionPerformed
        // TODO add your handling code here:
        //To clear fields
        txtBlockId.setText("  ");
        txtBlockSize.setText("  ");
        txtBlockCost.setText("  ");
        txtBlockEstValue.setText("  ");
    }//GEN-LAST:event_btnUndoBlockActionPerformed

    private void cmbUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUnitActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempActionPerformed
        // TODO add your handling code here:
        //To load existing data to table
        ResultSet rs=new DBSearch().searchblocks();
        DefaultTableModel dtm=(DefaultTableModel)tblLand1.getModel();
        dtm.setRowCount(0);
        try
        {
            Vector v=null;
            while(rs.next())
            {
                v=new Vector();
                v.add(rs.getString("BlockID"));
                v.add(rs.getString("BlockSize"));
                v.add(rs.getString("BlockCost"));
                v.add(rs.getString("BlockEstimatedValue"));
                v.add(rs.getString("BlockAvailability"));
                dtm.addRow(v);

            }
            DBCon.closeCon();

        }
        catch(Exception k)
        {

        }
    }//GEN-LAST:event_btnTempActionPerformed

    private void txtBlockCost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlockCost1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlockCost1ActionPerformed

    private void btnAddBlock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBlock1ActionPerformed
        //Update button events
        String Status = cmbUnit3.getSelectedItem().toString();

        EditControl.editBlock(txtBlockId1.getText(),txtBlockSize2.getText(),txtBlockCost1.getText(),txtBlockEstValue1.getText(),Status);
    }//GEN-LAST:event_btnAddBlock1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String BlockID=this.txtBlockId1.getText();
        
        if(BlockID.isEmpty()){
            JOptionPane.showMessageDialog(null, "Select a block");
        }
        else{
            int des = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this item?","Delete", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(des==0){
                //Delete record
                DeleteControl.deleteBlock(txtBlockId1.getText());
            }
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblLand2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLand2MouseClicked
        //show selected row data on form
        int i = tblLand2.getSelectedRow();
        TableModel model=tblLand2.getModel();
        txtBlockId1.setText(model.getValueAt(i,0).toString());
        txtBlockSize2.setText(model.getValueAt(i,1).toString());
        txtBlockCost1.setText(model.getValueAt(i,2).toString());
        txtBlockEstValue1.setText(model.getValueAt(i,3).toString());
        String Status=model.getValueAt(i,4).toString();
        switch (Status) {
            case "Yes":
            cmbUnit3.setSelectedIndex(0);
            break;
            case "No":
            cmbUnit3.setSelectedIndex(1);
            break;
        }
    }//GEN-LAST:event_tblLand2MouseClicked

    private void txtBlockSize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlockSize2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlockSize2ActionPerformed

    private void cmbUnit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUnit2ActionPerformed

    private void cmbUnit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUnit3ActionPerformed

    private void btnTemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemp1ActionPerformed
        // TODO add your handling code here:
        //To load existing data to table
        ResultSet rs=new DBSearch().searchblocks();
        DefaultTableModel dtm1=(DefaultTableModel)tblLand2.getModel();
        dtm1.setRowCount(0);
        try
        {
            Vector v=null;
            while(rs.next())
            {
                v=new Vector();
                v.add(rs.getString("BlockID"));
                v.add(rs.getString("BlockSize"));
                v.add(rs.getString("BlockCost"));
                v.add(rs.getString("BlockEstimatedValue"));
                v.add(rs.getString("BlockAvailability"));
                dtm1.addRow(v);

            }
            DBCon.closeCon();

        }
        catch(Exception k)
        {

        }
    }//GEN-LAST:event_btnTemp1ActionPerformed

    private void txtBlockEstValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlockEstValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlockEstValueActionPerformed

    private void prdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prdActionPerformed
        // TODO add your handling code here:
        stmt=(Statement) DBCon.getStatementConnection();
        try{
        rs = stmt.executeQuery("SELECT LandID FROM blockandlandtable"+prd.getSelectedItem());
        }
        catch(Exception e)
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_prdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBlock;
    private javax.swing.JButton btnAddBlock1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTemp;
    private javax.swing.JButton btnTemp1;
    private javax.swing.JButton btnUndoBlock;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbUnit;
    private javax.swing.JComboBox<String> cmbUnit2;
    private javax.swing.JComboBox<String> cmbUnit3;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lblAddBlock;
    private javax.swing.JLabel lblAddBlock1;
    private javax.swing.JLabel lblBlockAvailability;
    private javax.swing.JLabel lblBlockAvailability1;
    private javax.swing.JLabel lblBlockCost;
    private javax.swing.JLabel lblBlockCost1;
    private javax.swing.JLabel lblBlockEstValue;
    private javax.swing.JLabel lblBlockEstValue1;
    private javax.swing.JLabel lblBlockId;
    private javax.swing.JLabel lblBlockId1;
    private javax.swing.JLabel lblBlockId2;
    private javax.swing.JLabel lblBlockSize;
    private javax.swing.JLabel lblBlockSize1;
    private javax.swing.JLabel lblLandManagement;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBlock;
    private javax.swing.JPanel pnlEditBlock;
    private javax.swing.JPanel pnlNewBlock;
    private javax.swing.JPanel pnlNewBlock1;
    private javax.swing.JComboBox<String> prd;
    private javax.swing.JTable tblLand1;
    private javax.swing.JTable tblLand2;
    private javax.swing.JTabbedPane tbpBlock;
    private javax.swing.JTextField txtBlockCost;
    private javax.swing.JTextField txtBlockCost1;
    private javax.swing.JTextField txtBlockEstValue;
    private javax.swing.JTextField txtBlockEstValue1;
    private javax.swing.JTextField txtBlockId;
    private javax.swing.JTextField txtBlockId1;
    private javax.swing.JTextField txtBlockSize;
    private javax.swing.JTextField txtBlockSize2;
    // End of variables declaration//GEN-END:variables
}
