/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.BlockControl1;
import Control.DeleteControl;
import Control.EditControl1;
import Model.DBCon;
import Model.DBSearch;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.text.DecimalFormat;

/**
 *
 * @author pc
 */
public class Block1 extends javax.swing.JInternalFrame {
    int Numberofblocks;
    int Frequency;
    /**
     * Creates new form Projects
     */
    public Block1() {
        initComponents();
        String UserRole=Home1.UserRole;
        
        disable(UserRole);
        
        LoadId();
        loadBlocks();
        loadfil();
    }
    
    
    public void loadBlocks(){
        ResultSet rs=new DBSearch().searchblocks();
         DefaultTableModel dtm=(DefaultTableModel)tblLand1.getModel();
         DefaultTableModel dtm1=(DefaultTableModel)tblLand2.getModel();
        dtm.setRowCount(0);
        dtm1.setRowCount(0);
        try
        {
            Vector v=null;
            while(rs.next())
            {
                v=new Vector();
                v.add(rs.getString("BlockID"));
                v.add(rs.getString("BlockSizeAcres"));
                v.add(rs.getString("BlockSizeRoods"));
                v.add(rs.getString("BlockSizePerches"));
                v.add(rs.getString("PriceOfPerch"));
                v.add(rs.getString("BlockEstimatedValue"));
                v.add(rs.getString("BlockAvailability"));
                dtm.addRow(v);
                dtm1.addRow(v);
            }
             DBCon.closeCon();
            
        }
        catch(Exception k)
        {
            
        }   
    }
    
    public void LoadId(){
        DBSearch obj = new DBSearch();
        ResultSet rs = obj.LoadId();
        
        try{
            while(rs.next()){
                this.jComboBox1.addItem(rs.getString("LandID"));
            }
        }
        catch(Exception ex){
            System.out.println("Error"+ex.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        tbpBlock = new javax.swing.JTabbedPane();
        pnlBlock = new javax.swing.JPanel();
        pnlNewBlock = new javax.swing.JPanel();
        lblAddBlock = new javax.swing.JLabel();
        lblBlockId = new javax.swing.JLabel();
        txtBlockId = new javax.swing.JTextField();
        lblBlockSize = new javax.swing.JLabel();
        txtAcres = new javax.swing.JTextField();
        txtBlockEstValue = new javax.swing.JTextField();
        lblBlockAvailability = new javax.swing.JLabel();
        btnAddBlock = new javax.swing.JButton();
        btnUndoBlock = new javax.swing.JButton();
        lblBlockCost = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLand1 = new javax.swing.JTable();
        cmbStatus = new javax.swing.JComboBox<>();
        lblProIdNew = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblAcres = new javax.swing.JLabel();
        lblRoods = new javax.swing.JLabel();
        lblPerches = new javax.swing.JLabel();
        txtRoods = new javax.swing.JTextField();
        txtPerches = new javax.swing.JTextField();
        lblPerchPrice = new javax.swing.JLabel();
        txtPerchPrice = new javax.swing.JTextField();
        lblExceed = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pnlEditBlock = new javax.swing.JPanel();
        pnlNewBlock1 = new javax.swing.JPanel();
        lblAddBlock1 = new javax.swing.JLabel();
        txtBlockId1 = new javax.swing.JTextField();
        lblBlockSize1 = new javax.swing.JLabel();
        txtBlockEstValue1 = new javax.swing.JTextField();
        lblBlockAvailability1 = new javax.swing.JLabel();
        btnAddBlock1 = new javax.swing.JButton();
        btnUndoBlock1 = new javax.swing.JButton();
        lblBlockCost1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLand2 = new javax.swing.JTable();
        cmbUnit3 = new javax.swing.JComboBox<>();
        lblAcres1 = new javax.swing.JLabel();
        lblRoods1 = new javax.swing.JLabel();
        lblPerches1 = new javax.swing.JLabel();
        txtAcres1 = new javax.swing.JTextField();
        txtRoods1 = new javax.swing.JTextField();
        txtPerches1 = new javax.swing.JTextField();
        lblPerchPrice1 = new javax.swing.JLabel();
        txtPerchPrice1 = new javax.swing.JTextField();
        lblBlockId1 = new javax.swing.JLabel();
        lblLandManagement = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        lID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(null);
        setMinimumSize(null);

        pnlBase.setMaximumSize(null);

        tbpBlock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        pnlBlock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        pnlNewBlock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddBlock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddBlock.setText("Add A New Land Block");
        pnlNewBlock.add(lblAddBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 9, -1, -1));

        lblBlockId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockId.setText("Block Id");
        pnlNewBlock.add(lblBlockId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 154, -1, -1));
        pnlNewBlock.add(txtBlockId, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 153, 191, -1));

        lblBlockSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockSize.setText("Size");
        pnlNewBlock.add(lblBlockSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 234, 75, -1));

        txtAcres.setText("0");
        txtAcres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAcresMouseClicked(evt);
            }
        });
        txtAcres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcresActionPerformed(evt);
            }
        });
        txtAcres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAcresKeyPressed(evt);
            }
        });
        pnlNewBlock.add(txtAcres, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 262, 84, 36));

        txtBlockEstValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBlockEstValueMouseClicked(evt);
            }
        });
        txtBlockEstValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlockEstValueActionPerformed(evt);
            }
        });
        pnlNewBlock.add(txtBlockEstValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 327, 193, 36));

        lblBlockAvailability.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockAvailability.setText("Availability");
        pnlNewBlock.add(lblBlockAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 378, 130, -1));

        btnAddBlock.setBackground(new java.awt.Color(0, 102, 102));
        btnAddBlock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddBlock.setText("Add");
        btnAddBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBlockActionPerformed(evt);
            }
        });
        pnlNewBlock.add(btnAddBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 422, 166, 42));

        btnUndoBlock.setBackground(new java.awt.Color(0, 102, 102));
        btnUndoBlock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUndoBlock.setText("Clear");
        btnUndoBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoBlockActionPerformed(evt);
            }
        });
        pnlNewBlock.add(btnUndoBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 422, 166, 42));

        lblBlockCost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockCost.setText("Cost");
        pnlNewBlock.add(lblBlockCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 332, 75, -1));

        tblLand1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Block ID", "Acres", "Roods", "Perches", "Price of Perch", "Cost", "Availability"
            }
        ));
        jScrollPane2.setViewportView(tblLand1);

        pnlNewBlock.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 59, 982, 405));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        pnlNewBlock.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 378, 193, -1));

        lblProIdNew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProIdNew.setText("Project Id");
        pnlNewBlock.add(lblProIdNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, -1, -1));

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        pnlNewBlock.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 59, 191, -1));

        lblAcres.setText("Acres");
        pnlNewBlock.add(lblAcres, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 239, -1, -1));

        lblRoods.setText("Roods");
        pnlNewBlock.add(lblRoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 239, -1, -1));

        lblPerches.setText("Perches");
        pnlNewBlock.add(lblPerches, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 239, -1, -1));

        txtRoods.setText("0");
        txtRoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRoodsMouseClicked(evt);
            }
        });
        txtRoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoodsActionPerformed(evt);
            }
        });
        pnlNewBlock.add(txtRoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 262, 84, 36));

        txtPerches.setText("0");
        txtPerches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPerchesMouseClicked(evt);
            }
        });
        txtPerches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerchesActionPerformed(evt);
            }
        });
        pnlNewBlock.add(txtPerches, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 262, 84, 36));

        lblPerchPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPerchPrice.setText("Price of Perch");
        pnlNewBlock.add(lblPerchPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 201, -1, -1));

        txtPerchPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerchPriceActionPerformed(evt);
            }
        });
        txtPerchPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPerchPriceKeyPressed(evt);
            }
        });
        pnlNewBlock.add(txtPerchPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 200, 191, -1));
        pnlNewBlock.add(lblExceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 91, 191, 33));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Filter By Project");
        pnlNewBlock.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 150, 30));

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnlNewBlock.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 18, 280, 30));

        javax.swing.GroupLayout pnlBlockLayout = new javax.swing.GroupLayout(pnlBlock);
        pnlBlock.setLayout(pnlBlockLayout);
        pnlBlockLayout.setHorizontalGroup(
            pnlBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBlockLayout.createSequentialGroup()
                .addComponent(pnlNewBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
        );
        pnlBlockLayout.setVerticalGroup(
            pnlBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNewBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        tbpBlock.addTab("+New", pnlBlock);

        lblAddBlock1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddBlock1.setText("Edit A Land Block");

        lblBlockSize1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockSize1.setText("Size");

        txtBlockEstValue1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBlockEstValue1MouseClicked(evt);
            }
        });

        lblBlockAvailability1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockAvailability1.setText("Availability");

        btnAddBlock1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddBlock1.setText("Update");
        btnAddBlock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBlock1ActionPerformed(evt);
            }
        });

        btnUndoBlock1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUndoBlock1.setText("Delete");
        btnUndoBlock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoBlock1ActionPerformed(evt);
            }
        });

        lblBlockCost1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockCost1.setText("Cost");

        tblLand2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Block ID", "Acres", "Roods", "Perches", "Price of Perch", "Cost", "Availability"
            }
        ));
        tblLand2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLand2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLand2);

        cmbUnit3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbUnit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnit3ActionPerformed(evt);
            }
        });

        lblAcres1.setText("Acres");

        lblRoods1.setText("Roods");

        lblPerches1.setText("Perches");

        txtAcres1.setText("0");
        txtAcres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcres1ActionPerformed(evt);
            }
        });

        txtRoods1.setText("0");
        txtRoods1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoods1ActionPerformed(evt);
            }
        });

        txtPerches1.setText("0");
        txtPerches1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerches1ActionPerformed(evt);
            }
        });

        lblPerchPrice1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPerchPrice1.setText("Price of Perch");

        txtPerchPrice1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPerchPrice1KeyPressed(evt);
            }
        });

        lblBlockId1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlockId1.setText("Block Id");

        javax.swing.GroupLayout pnlNewBlock1Layout = new javax.swing.GroupLayout(pnlNewBlock1);
        pnlNewBlock1.setLayout(pnlNewBlock1Layout);
        pnlNewBlock1Layout.setHorizontalGroup(
            pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                .addComponent(lblBlockSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(lblAcres1)
                                .addGap(61, 61, 61)
                                .addComponent(lblRoods1)
                                .addGap(64, 64, 64)
                                .addComponent(lblPerches1))
                            .addComponent(lblBlockId1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                    .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                        .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(lblAddBlock1))
                            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddBlock1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(txtAcres1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPerchPrice1)
                                    .addComponent(lblBlockAvailability1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBlockCost1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnUndoBlock1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbUnit3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBlockEstValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPerchPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                                            .addComponent(txtRoods1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtPerches1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtBlockId1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlNewBlock1Layout.setVerticalGroup(
            pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAddBlock1)
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewBlock1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBlockId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblBlockId1)
                        .addGap(45, 45, 45)))
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerchPrice1)
                    .addComponent(txtPerchPrice1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlockSize1)
                    .addComponent(lblPerches1)
                    .addComponent(lblRoods1)
                    .addComponent(lblAcres1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerches1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRoods1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcres1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBlockEstValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBlockCost1))
                .addGap(50, 50, 50)
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBlockAvailability1)
                    .addComponent(cmbUnit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(pnlNewBlock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUndoBlock1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBlock1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(pnlNewBlock1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlEditBlockLayout = new javax.swing.GroupLayout(pnlEditBlock);
        pnlEditBlock.setLayout(pnlEditBlockLayout);
        pnlEditBlockLayout.setHorizontalGroup(
            pnlEditBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNewBlock1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlEditBlockLayout.setVerticalGroup(
            pnlEditBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditBlockLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlNewBlock1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        tbpBlock.addTab("Update", pnlEditBlock);

        lblLandManagement.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblLandManagement.setText("Manage Block");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(lblLandManagement)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(362, 362, 362)
                                .addComponent(lID)
                                .addGap(69, 69, 69)
                                .addComponent(jButton1))
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(tbpBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 1565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lID)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(tbpBlock)
                .addGap(277, 277, 277))
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLandManagement)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAcresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcresActionPerformed

    private void btnAddBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBlockActionPerformed
        // TODO add your handling code here:
        // Get data from fields
        String BlockID= txtBlockId.getText().toString();
        String BlockSizeAcres= txtAcres.getText().toString();
        String BlockSizeRoods= txtRoods.getText().toString();
        String BlockSizePerches= txtPerches.getText().toString();
        String PerchPrice= txtPerchPrice.getText().toString();
        String EstValue= txtBlockEstValue.getText().toString();
                 
        
     if(BlockID.isEmpty()||EstValue.isEmpty()){
         JOptionPane.showMessageDialog(null,"Enter valid details.");
     }
     
     else if(Numberofblocks<Frequency){
         JOptionPane.showMessageDialog(null,"Number of blocks have been exceeded. Cannot add record.");
     }
     else
     {
      
        String Id = jComboBox1.getSelectedItem().toString();
        String Status = cmbStatus.getSelectedItem().toString();
        
        BlockControl1.addLandAndBlock(Id,txtBlockId.getText());
        BlockControl1.addBlocks(BlockID,Id,BlockSizeAcres,BlockSizeRoods,BlockSizePerches,PerchPrice,EstValue,Status);
     }
        
     loadBlocks();
     
     txtBlockId.setText("");
     txtAcres.setText("0");
     txtRoods.setText("0");
     txtPerches.setText("0");
     txtBlockEstValue.setText("0");
     txtBlockEstValue.setText("");
     txtPerchPrice.setText("");
     
     
     
     
     
     
     
    }//GEN-LAST:event_btnAddBlockActionPerformed

    private void btnUndoBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoBlockActionPerformed
        // TODO add your handling code here:
       //To clear fields
        txtBlockId.setText("");
        txtAcres.setText("0");
        txtRoods.setText("0");
        txtPerches.setText("0");
        txtPerchPrice.setText("");
        txtBlockEstValue.setText("");
    }//GEN-LAST:event_btnUndoBlockActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        DBSearch obj = new DBSearch();
        DBSearch obj1 = new DBSearch();
        
        String LandId = jComboBox1.getSelectedItem().toString();
        
        ResultSet rs = obj.searchcount(LandId);
        ResultSet rs1=obj1. searchaproject(LandId);
        
        int flag=0; String Frq="";
        int flag1=0; String NumBlock="";
        
        try{
            while(rs.next())
            {
                Frq=rs.getString("Frequency");//DB table colum name

                flag=1;

                if(flag==1){
                    this.lblExceed.setText("This project has "+Frq+" blocks.");
                }

            }
        }catch(Exception k){
            System.out.println("error"+ k.toString());

        }

        try{
            while(rs1.next())
            {
                NumBlock=rs1.getString("NumberOfBlocks");//DB table colum name

                flag1=1;

                if(flag1==1){
                    int numberofblocks = Integer.parseInt(NumBlock);
                    int frequency = Integer.parseInt(Frq);
                    int remain = numberofblocks-frequency;
                    this.lblExceed.setText("Remaining Blocks: "+remain);
                    
                    if(numberofblocks<frequency){
                        this.lblExceed.setText("");
                        this.lblExceed.setText("Remaining Blocks: 0");
                   }
                    Numberofblocks=numberofblocks;
                    Frequency=frequency;
                }
            }
        }catch(Exception k){
            System.out.println("error"+ k.toString());

        }              
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtRoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoodsActionPerformed

    private void txtPerchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerchesActionPerformed

    private void btnAddBlock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBlock1ActionPerformed
        // TODO add your handling code here:
       //Update button events
        String Status = cmbUnit3.getSelectedItem().toString();

        EditControl1.editBlock1(txtBlockId1.getText(),txtAcres1.getText(),txtRoods1.getText(),txtPerches1.getText(),txtPerchPrice1.getText(),txtBlockEstValue1.getText(),Status);
        EditControl1.editBlock(txtBlockId1.getText(),txtAcres1.getText(),txtRoods1.getText(),txtPerches1.getText(),txtPerchPrice1.getText(),txtBlockEstValue1.getText(),Status);

        loadBlocks();
    }//GEN-LAST:event_btnAddBlock1ActionPerformed

    private void btnUndoBlock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoBlock1ActionPerformed
        // TODO add your handling code here:
        String BlockID=this.txtBlockId1.getText();
        
        if(BlockID.isEmpty()){
            JOptionPane.showMessageDialog(null, "Select a block");
        }
        else{
            int des = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this Block?","Delete", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(des==0){
                //Delete record
                DeleteControl.deleteBlock(txtBlockId1.getText());
                DeleteControl.deleteBlock1(txtBlockId1.getText());
            }
        }
       //Clear fields
        txtBlockId1.setText("");
        txtAcres1.setText("0");
        txtRoods1.setText("0");
        txtPerches1.setText("0");
        txtPerchPrice1.setText("");
        txtBlockEstValue1.setText("");
        
        loadBlocks();
    }//GEN-LAST:event_btnUndoBlock1ActionPerformed

    private void tblLand2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLand2MouseClicked
        //show selected row data on form
        int i = tblLand2.getSelectedRow();
        TableModel model=tblLand2.getModel();
        txtBlockId1.setText(model.getValueAt(i,0).toString());
        txtAcres1.setText(model.getValueAt(i,1).toString());
        txtRoods1.setText(model.getValueAt(i,2).toString());
        txtPerches1.setText(model.getValueAt(i,3).toString());  
        txtPerchPrice1.setText(model.getValueAt(i,4).toString());
        txtBlockEstValue1.setText(model.getValueAt(i,5).toString());
        String Status=model.getValueAt(i,6).toString();
        switch (Status) {
            case "Yes":
            cmbUnit3.setSelectedIndex(0);
            break;
            case "No":
            cmbUnit3.setSelectedIndex(1);
            break;
        }
    }//GEN-LAST:event_tblLand2MouseClicked

    private void cmbUnit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUnit3ActionPerformed

    private void txtAcres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcres1ActionPerformed

    private void txtRoods1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoods1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoods1ActionPerformed

    private void txtPerches1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerches1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerches1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPerchPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerchPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerchPriceActionPerformed

    private void txtPerchPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPerchPriceKeyPressed
        // TODO add your handling code here:
      /* double Acres = Double.parseDouble(txtAcres1.getText());
        double Roods = Double.parseDouble(txtRoods1.getText());
        double Perches = Double.parseDouble(txtPerches1.getText());
        double PerchPrice = Double.parseDouble(txtPerchPrice1.getText());
        
        double EstVal = (Acres*160+Roods*40+Perches)*PerchPrice*10;
        //DecimalFormat df =new DecimalFormat("###.##");
        txtBlockEstValue1.setText(""+EstVal);*/
    }//GEN-LAST:event_txtPerchPriceKeyPressed

    private void txtPerchPrice1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPerchPrice1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPerchPrice1KeyPressed

    private void txtBlockEstValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlockEstValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlockEstValueActionPerformed

    private void txtAcresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcresKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcresKeyPressed

    private void txtBlockEstValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBlockEstValueMouseClicked
        // TODO add your handling code here:
        String A = txtAcres.getText();
        String R = txtRoods.getText();
        String P = txtPerches.getText();
        
        if(A.isEmpty()){
            txtAcres.setText("0");
        }
        if(R.isEmpty()){
            txtRoods.setText("0");
        }
        if(P.isEmpty()){
            txtPerches.setText("0");
        }
        
        double Acres = Double.parseDouble(txtAcres.getText());
        double Roods = Double.parseDouble(txtRoods.getText());
        double Perches = Double.parseDouble(txtPerches.getText());
        double PerchPrice = Double.parseDouble(txtPerchPrice.getText());
        
        double Ac = Acres*160;
        double Ro = Roods*40;
        double Pe = Perches*1;
        
        txtBlockEstValue.setText(""+(Ac+Ro+Pe)*PerchPrice+"0");
    }//GEN-LAST:event_txtBlockEstValueMouseClicked

    private void txtBlockEstValue1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBlockEstValue1MouseClicked
        // TODO add your handling code here:
        double Acres = Double.parseDouble(txtAcres1.getText());
        double Roods = Double.parseDouble(txtRoods1.getText());
        double Perches = Double.parseDouble(txtPerches1.getText());
        double PerchPrice = Double.parseDouble(txtPerchPrice1.getText());
        
        double Ac = Acres*160;
        double Ro = Roods*40;
        double Pe = Perches*1;
        
        txtBlockEstValue1.setText(""+(Ac+Ro+Pe)*PerchPrice);
    }//GEN-LAST:event_txtBlockEstValue1MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        
        
         
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void txtAcresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAcresMouseClicked
        // TODO add your handling code here:
        txtAcres.setText("");
    }//GEN-LAST:event_txtAcresMouseClicked

    private void txtRoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRoodsMouseClicked
        // TODO add your handling code here:
        txtRoods.setText("");
    }//GEN-LAST:event_txtRoodsMouseClicked

    private void txtPerchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPerchesMouseClicked
        // TODO add your handling code here:
        txtPerches.setText("");
    }//GEN-LAST:event_txtPerchesMouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
         DBSearch obj=new DBSearch();
       String projid=(String) this.jTextField1.getText();
        
        
        ResultSet rs=obj.filterble(projid);
        DefaultTableModel dtm=(DefaultTableModel)tblLand1.getModel();
        dtm.setRowCount(0);
        Vector z;

        try{
            while(rs.next()){
                z=new Vector();
                z.add(rs.getString("BlockID"));
                z.add(rs.getString("BlockSizeAcres"));
                z.add(rs.getString("BlockSizeRoods"));
                z.add(rs.getString("BlockSizePerches"));
                z.add(rs.getString("BlockEstimatedValue"));
                z.add(rs.getString("BlockAvailability"));
                

                dtm.addRow(z);

            }

        }
        catch(Exception k){
            System.out.println("Error"+k.toString());
        }
        
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    public void disable(String UserRole){
        if(UserRole.equals("User")){
            btnUndoBlock1.setEnabled(false);
        }
        else{
            btnUndoBlock1.setEnabled(true);
        }
    }
    public void loadfil()
    {
       DBSearch obj=new DBSearch();
    ResultSet rs=obj.Loadfilter(); 
    
      try{
            while(rs.next()){
               // this.jComboBox2.addItem(rs.getString("Proid"));
                
            }
            
        }
        catch(Exception k){
            System.out.println("Error"+k.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBlock;
    private javax.swing.JButton btnAddBlock1;
    private javax.swing.JButton btnUndoBlock;
    private javax.swing.JButton btnUndoBlock1;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbUnit3;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lID;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lblAcres;
    private javax.swing.JLabel lblAcres1;
    private javax.swing.JLabel lblAddBlock;
    private javax.swing.JLabel lblAddBlock1;
    private javax.swing.JLabel lblBlockAvailability;
    private javax.swing.JLabel lblBlockAvailability1;
    private javax.swing.JLabel lblBlockCost;
    private javax.swing.JLabel lblBlockCost1;
    private javax.swing.JLabel lblBlockId;
    private javax.swing.JLabel lblBlockId1;
    private javax.swing.JLabel lblBlockSize;
    private javax.swing.JLabel lblBlockSize1;
    private javax.swing.JLabel lblExceed;
    private javax.swing.JLabel lblLandManagement;
    private javax.swing.JLabel lblPerchPrice;
    private javax.swing.JLabel lblPerchPrice1;
    private javax.swing.JLabel lblPerches;
    private javax.swing.JLabel lblPerches1;
    private javax.swing.JLabel lblProIdNew;
    private javax.swing.JLabel lblRoods;
    private javax.swing.JLabel lblRoods1;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBlock;
    private javax.swing.JPanel pnlEditBlock;
    private javax.swing.JPanel pnlNewBlock;
    private javax.swing.JPanel pnlNewBlock1;
    private javax.swing.JTable tblLand1;
    private javax.swing.JTable tblLand2;
    private javax.swing.JTabbedPane tbpBlock;
    private javax.swing.JTextField txtAcres;
    private javax.swing.JTextField txtAcres1;
    private javax.swing.JTextField txtBlockEstValue;
    private javax.swing.JTextField txtBlockEstValue1;
    private javax.swing.JTextField txtBlockId;
    private javax.swing.JTextField txtBlockId1;
    private javax.swing.JTextField txtPerchPrice;
    private javax.swing.JTextField txtPerchPrice1;
    private javax.swing.JTextField txtPerches;
    private javax.swing.JTextField txtPerches1;
    private javax.swing.JTextField txtRoods;
    private javax.swing.JTextField txtRoods1;
    // End of variables declaration//GEN-END:variables
}
